changesetBaseRefs:
  - main
  - origin/main
  - upstream/main

packageExtensions:
  "@apollo/client@*":
    dependencies:
      graphql: "*"
  "@apollographql/apollo-tools@*":
    dependencies:
      graphql: "*"
  "@webpack-cli/serve@*":
    dependencies:
      webpack-dev-server: "*"
  nunjucks-date-filter@*:
    dependencies:
      nunjucks: "*"
  rc-animate@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-cascader@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-checkbox@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-collapse@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-dialog@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-input-number@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-menu@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-progress@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-rate@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-tabs@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-tooltip@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-trigger@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-upload@*:
    dependencies:
      react: "*"
      react-dom: "*"
  rc-util@*:
    dependencies:
      react: "*"
      react-dom: "*"
  react-dom@*:
    dependencies:
      react: "*"
  webpack-dev-server@*:
    dependencies:
      webpack: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
