packageExtensions:
  "@apollo/client@*":
    dependencies:
      graphql: "*"
  "@apollographql/apollo-tools@*":
    dependencies:
      graphql: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-berry.cjs
