packageExtensions:
  '@apollo/client@*':
    dependencies:
      graphql: '*'
  '@apollographql/apollo-tools@*':
    dependencies:
      graphql: '*'
  'rc-animate@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-dialog@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-cascader@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-checkbox@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-collapse@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-input-number@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-menu@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-progress@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-rate@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-tabs@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-tooltip@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-trigger@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-upload@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'rc-util@*':
    dependencies:
      'react-dom': '*'
      'react': '*'
  'react-dom@*':
    dependencies:
      'react': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.cjs
