name: Test NPM Publish

on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: https://registry.npmjs.org/
      - uses: actions/checkout@v2

      - name: yarn install
        run: yarn install

      - name: yarn build
        run: yarn build

      - name: publish to npm
        run: yarn lerna publish from-package ---ignore-scripts --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
