name: Test

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - uses: actions/checkout@v2
      - name: Check yarn cache integrity
        run: yarn install --immutable --immutable-cache
      - name: Build packages
        run: yarn build
      - name: Test packages
        run: yarn test
